### ISSUE TITLE
Importing data to Splunk

### ISSUE THREAD

**Issue by smalluk** [CiscoSecurity/gta-03-api-use-cases#8]
To import to Splunk am I required to create my own app using the Splunk add-on builder?
Are there any further instructions that are not included in the Readme? It is quite sparse in regards to Splunk integration.

**Comment by smalluk** [comment]
Can you advise on how to input the proxy details to allow the app to connect to the Cisco URL's? This is for Splunk log onboarding

**Comment by bredy** [comment]
Hello, sorry for late response.

To import data to Splunk you don't need to create own Splunk app, it's just enough to use the scripted inputs data source as described here https://docs.splunk.com/Documentation/Splunk/latest/Data/Getdatafromscriptedinputs .

Script "[get_security_annotations.py](https://github.com/CiscoSecurity/gta-03-api-use-cases/blob/main/get_security_annotations.py)" can be used directly or can be used as template and modified according to your needs. It uses "[api_client.py](https://github.com/CiscoSecurity/gta-03-api-use-cases/blob/main/api_client.py)" where are already defined our Cisco endpoints. You just need to define your SecureX credentials defined in "[authentication](https://github.com/CiscoSecurity/gta-03-api-use-cases#authentication)" section.

**Comment by smalluk** [comment]
Thank you @bredy
